syncthing:
  puid: 1000
  pgid: 1000
  podDistribution: cluster # can be "spread" or "cluster"
  enabled: true
  container:
    image: linuxserver/syncthing
    tag: latest
  service:
    type: NodePort
    ports:
      - port: 22000
        targetPort: 22000
        protocol: TCP
        name: tcp
        nodeport: 30489
      - port: 22000
        targetPort: 22000
        protocol: UDP
        name: udp
        nodeport: 30479
      - port: 21027
        targetPort: 21027
        nodeport: 32752
        protocol: UDP
        name: discovery
  uiservice:
    type: LoadBalancer  
    ports:
      - port: 8384
        targetPort: 8384
        protocol: TCP
        name: http
  configVolume:
    name: sync-config
    storageClassName: longhorn
    annotations: {}
    labels: {}
    accessModes: ReadWriteOnce
    storage: 10Gi
    selector: {}
  syncVolume:
    name: syncthing
    storageClassName: longhorn
    annotations: {}
    labels: {}
    accessModes: ReadWriteOnce
    storage: 10Gi
    selector: {}  